export const weapons = [{
        "id": "ck9kh54dk000015ylenofhe33",
        "name": "†Great sword (6')",
        "category": "Swords",
        "type": "Class I: Straight Swords",
        "dice": 6,
        "adds": "",
        "strengthReq": 21,
        "dexReq": 18,
        "cost": 120,
        "weight": 170,
        "range": "",
        "length": "",
        "extraInfo": ""
    },
    {
        "id": "ck9kh671i000115ylzyr1cgqy",
        "name": "†Two-handed broadsword (5')",
        "category": "Swords",
        "type": "Class I: Straight Swords",
        "dice": 5,
        "adds": "2",
        "strengthReq": 21,
        "dexReq": 14,
        "cost": 110,
        "weight": 160,
        "range": "",
        "length": "",
        "extraInfo": ""
    },
    {
        "id": "ck9kh7zn5000215yl6uvh53en",
        "name": "Hand-and-a-half sword (4')",
        "category": "Swords",
        "type": "Class I: Straight Swords",
        "dice": 5,
        "adds": "",
        "strengthReq": 16,
        "dexReq": 12,
        "cost": 90,
        "weight": 150,
        "range": "",
        "length": "",
        "extraInfo": ""
    },
    {
        "id": "ck9kha1z3000315ylub3oijqv",
        "name": "Broadsword (3'-4')",
        "category": "Swords",
        "type": "Class I: Straight Swords",
        "dice": 3,
        "adds": "4",
        "strengthReq": 15,
        "dexReq": 10,
        "cost": 70,
        "weight": 120,
        "range": "",
        "length": "",
        "extraInfo": ""
    },
    {
        "id": "ck9khd1nv000415yla9s9bbvn",
        "name": "Gladius (2.5'-3')",
        "category": "Swords",
        "type": "Class I: Straight Swords",
        "dice": 3,
        "adds": "2",
        "strengthReq": 10,
        "dexReq": 7,
        "cost": 50,
        "weight": 70,
        "range": "",
        "length": "",
        "extraInfo": ""
    },
    {
        "id": "ck9khh2q6000515yl8wc5gfvq",
        "name": "Short sword (2'-2.5')",
        "category": "Swords",
        "type": "Class I: Straight Swords",
        "dice": 3,
        "adds": "",
        "strengthReq": 7,
        "dexReq": 3,
        "cost": 35,
        "weight": 30,
        "range": "",
        "length": "",
        "extraInfo": ""
    },
    {
        "id": "ck9khj6is000615ylrazoowjf",
        "name": "†Grand Shamsheer (No-datchi) (6') ",
        "category": "Swords",
        "type": "Class II: Curved Swords",
        "dice": 6,
        "adds": "2",
        "strengthReq": 22,
        "dexReq": 18,
        "cost": 135,
        "weight": 150,
        "range": "",
        "length": "",
        "extraInfo": ""
    },
    {
        "id": "ck9khkzwd000715yli5pfsqkf",
        "name": "†Double-bladed broad axe",
        "category": "Hafted Weapons",
        "type": "Class I: Slicing Heads",
        "dice": 6,
        "adds": "3",
        "strengthReq": 21,
        "dexReq": 10,
        "cost": 140,
        "weight": 220,
        "range": "",
        "length": "",
        "extraInfo": ""
    },
    {
        "id": "ck9khmmv7000815ylvi27typc",
        "name": "†Great axe (single blade)",
        "category": "Hafted Weapons",
        "type": "Class I: Slicing Heads",
        "dice": 5,
        "adds": "3",
        "strengthReq": 20,
        "dexReq": 10,
        "cost": 140,
        "weight": 220,
        "range": "",
        "length": "",
        "extraInfo": ""
    },
    {
        "id": "ck9khnw9t000915ylpzzohfca",
        "name": "†Bullova",
        "category": "Hafted Weapons",
        "type": "Class I: Slicing Heads",
        "dice": 4,
        "adds": "3",
        "strengthReq": 16,
        "dexReq": 9,
        "cost": 100,
        "weight": 200,
        "range": "",
        "length": "",
        "extraInfo": ""
    },
    {
        "id": "ck9khpu1t001015ylxnlamvfe",
        "name": "Broadaxe (single blade)",
        "category": "Hafted Weapons",
        "type": "Class I: Slicing Heads",
        "dice": 4,
        "adds": "",
        "strengthReq": 17,
        "dexReq": 8,
        "cost": 100,
        "weight": 150,
        "range": "",
        "length": "",
        "extraInfo": ""
    },
    {
        "id": "ck9khs5je001115ylhdqitazd",
        "name": "Francisca",
        "category": "Hafted Weapons",
        "type": "Class I: Slicing Heads",
        "dice": 3,
        "adds": "2",
        "strengthReq": 9,
        "dexReq": 5,
        "cost": 70,
        "weight": 60,
        "range": "",
        "length": "",
        "extraInfo": "(can be thrown -- if so, DEX req. = 12, range = 25 yards)"
    },
    {
        "id": "ck9khu159001215ylsfsdwlw9",
        "name": "Taper axe",
        "category": "Hafted Weapons",
        "type": "Class I: Slicing Heads",
        "dice": 3,
        "adds": "",
        "strengthReq": 8,
        "dexReq": 4,
        "cost": 50,
        "weight": 70,
        "range": "",
        "length": "",
        "extraInfo": ""
    },
    {
        "id": "ck9khvt1e001315ylm78vx3p3",
        "name": "†Bec de Corbin",
        "category": "Hafted Weapons",
        "type": "Class II: Stabbing Heads",
        "dice": 6,
        "adds": "",
        "strengthReq": 18,
        "dexReq": 10,
        "cost": 125,
        "weight": 175,
        "range": "",
        "length": "",
        "extraInfo": ""
    },
    {
        "id": "ck9khx79w001415ylq5eojqw5",
        "name": "Poleaxe",
        "category": "Pole Weapons",
        "type": "",
        "dice": 7,
        "adds": "",
        "strengthReq": 14,
        "dexReq": 13,
        "cost": 210,
        "weight": 300,
        "range": "",
        "length": "10'",
        "extraInfo": ""
    },
    {
        "id": "ck9ki0pne001515yl5skkvcz5",
        "name": "Chauves souris",
        "category": "Pole Weapons",
        "type": "",
        "dice": 6,
        "adds": "5",
        "strengthReq": 15,
        "dexReq": 12,
        "cost": 250,
        "weight": 190,
        "range": "",
        "length": "12'",
        "extraInfo": ""
    },
    {
        "id": "ck9ki375g001615ylsgqxsm9v",
        "name": "Ranseur (runka)",
        "category": "Pole Weapons",
        "type": "",
        "dice": 6,
        "adds": "4",
        "strengthReq": 15,
        "dexReq": 10,
        "cost": 170,
        "weight": 180,
        "range": "",
        "length": "12'",
        "extraInfo": ""
    },
    {
        "id": "ck9ki50rg001715yl24acuw36",
        "name": "Halbard",
        "category": "Pole Weapons",
        "type": "",
        "dice": 6,
        "adds": "",
        "strengthReq": 16,
        "dexReq": 12,
        "cost": 200,
        "weight": 250,
        "range": "",
        "length": "10'",
        "extraInfo": ""
    },
    {
        "id": "ck9ki93tk001815ylwak1pd4g",
        "name": "Pike",
        "category": "Pole Weapons",
        "type": "",
        "dice": 6,
        "adds": "",
        "strengthReq": 15,
        "dexReq": 12,
        "cost": 160,
        "weight": 100,
        "range": "",
        "length": "12'",
        "extraInfo": ""
    },
    {
        "id": "ck9kiamjp001915ylvymdizei",
        "name": "Demi-lune (halfmoon)",
        "category": "Pole Weapons",
        "type": "",
        "dice": 5,
        "adds": "4",
        "strengthReq": 12,
        "dexReq": 20,
        "cost": 100,
        "weight": 150,
        "range": "",
        "length": "12'",
        "extraInfo": ""
    },
    {
        "id": "ck9kimzx7002015yln2ef9umi",
        "name": "Voulge",
        "category": "Pole Weapons",
        "type": "",
        "dice": 5,
        "adds": "1",
        "strengthReq": 15,
        "dexReq": 9,
        "cost": 160,
        "weight": 200,
        "range": "",
        "length": "10'",
        "extraInfo": ""
    },
    {
        "id": "ck9kin02f002115ylfob25n0z",
        "name": "Voulge",
        "category": "Pole Weapons",
        "type": "",
        "dice": 5,
        "adds": "1",
        "strengthReq": 15,
        "dexReq": 9,
        "cost": 160,
        "weight": 200,
        "range": "",
        "length": "10'",
        "extraInfo": ""
    },
    {
        "id": "ck9kio5fi002215ylov6qsezj",
        "name": "Fauchard",
        "category": "Pole Weapons",
        "type": "",
        "dice": 5,
        "adds": "",
        "strengthReq": 13,
        "dexReq": 10,
        "cost": 160,
        "weight": 180,
        "range": "",
        "length": "12'",
        "extraInfo": ""
    },
    {
        "id": "ck9kird90002315ylukfjmakd",
        "name": "Partizan",
        "category": "Pole Weapons",
        "type": "",
        "dice": 4,
        "adds": "5",
        "strengthReq": 15,
        "dexReq": 9,
        "cost": 140,
        "weight": 200,
        "range": "",
        "length": "8'",
        "extraInfo": ""
    },
    {
        "id": "ck9kiu3v1002415yl4n88pqgq",
        "name": "Guisarme",
        "category": "Pole Weapons",
        "type": "",
        "dice": 4,
        "adds": "4",
        "strengthReq": 14,
        "dexReq": 10,
        "cost": 135,
        "weight": 200,
        "range": "",
        "length": "9'",
        "extraInfo": ""
    },
    {
        "id": "ck9kiwpaa002515yllyu96w7g",
        "name": "Scythe (long)",
        "category": "Pole Weapons",
        "type": "",
        "dice": 4,
        "adds": "2",
        "strengthReq": 11,
        "dexReq": 7,
        "cost": 80,
        "weight": 150,
        "range": "",
        "length": "6'",
        "extraInfo": ""
    },
    {
        "id": "ck9kixej5002615ylj88zd1qz",
        "name": "Billhook",
        "category": "Pole Weapons",
        "type": "",
        "dice": 4,
        "adds": "",
        "strengthReq": 14,
        "dexReq": 8,
        "cost": 120,
        "weight": 190,
        "range": "",
        "length": "11'",
        "extraInfo": ""
    },
    {
        "id": "ck9kiyelw002715ylzt5098rj",
        "name": "Kumade (rake)",
        "category": "Pole Weapons",
        "type": "",
        "dice": 3,
        "adds": "3",
        "strengthReq": 10,
        "dexReq": 12,
        "cost": 75,
        "weight": 90,
        "range": "",
        "length": "5'",
        "extraInfo": ""
    },
    {
        "id": "ck9kizqmt002815yld0wyyk86",
        "name": "Brandestock",
        "category": "Pole Weapons",
        "type": "",
        "dice": 3,
        "adds": "1",
        "strengthReq": 17,
        "dexReq": 10,
        "cost": 200,
        "weight": 150,
        "range": "",
        "length": "6'",
        "extraInfo": ""
    },
    {
        "id": "ck9kj0kxm002915yl5ms20f6a",
        "name": "Extended Brandestock",
        "category": "Pole Weapons",
        "type": "",
        "dice": 4,
        "adds": "",
        "strengthReq": 19,
        "dexReq": 12,
        "cost": 280,
        "weight": 200,
        "range": "",
        "length": "9'",
        "extraInfo": ""
    },
    {
        "id": "ck9kj353f003015yl69coxdzz",
        "name": "Pilum",
        "category": "Spears",
        "type": "",
        "dice": 5,
        "adds": "",
        "strengthReq": 12,
        "dexReq": 8,
        "cost": 75,
        "weight": 100,
        "range": "20 yards",
        "length": "(5'-8')",
        "extraInfo": ""
    },
    {
        "id": "ck9kj4a2q003115yl70duja4c",
        "name": "Trident",
        "category": "Spears",
        "type": "",
        "dice": 4,
        "adds": "3",
        "strengthReq": 10,
        "dexReq": 10,
        "cost": 60,
        "weight": 75,
        "range": "10 yards",
        "length": "6'",
        "extraInfo": ""
    },
    {
        "id": "ck9kj5dx8003215yla5tp83tn",
        "name": "Hoko",
        "category": "Spears",
        "type": "",
        "dice": 4,
        "adds": "1",
        "strengthReq": 10,
        "dexReq": 12,
        "cost": 55,
        "weight": 90,
        "range": "0",
        "length": "6'",
        "extraInfo": ""
    },
    {
        "id": "ck9kj6pn8003315yly5f77w7j",
        "name": "Oxtongue (hasta)",
        "category": "Spears",
        "type": "",
        "dice": 4,
        "adds": "",
        "strengthReq": 10,
        "dexReq": 5,
        "cost": 80,
        "weight": 70,
        "range": "0",
        "length": "6'",
        "extraInfo": "(best used from horseback -- if so, add 2 dice to its roll)"
    },
    {
        "id": "ck9kj8aav003415ylecpawj1t",
        "name": "†Spontoon",
        "category": "Spears",
        "type": "",
        "dice": 3,
        "adds": "3",
        "strengthReq": 9,
        "dexReq": 9,
        "cost": 30,
        "weight": 100,
        "range": "0",
        "length": "8'",
        "extraInfo": ""
    },
    {
        "id": "ck9kj8yu9003515ylo3wvsfki",
        "name": "Common spear",
        "category": "Spears",
        "type": "",
        "dice": 3,
        "adds": "1",
        "strengthReq": 8,
        "dexReq": 8,
        "cost": 22,
        "weight": 50,
        "range": "40 yards",
        "length": "6'",
        "extraInfo": ""
    },
    {
        "id": "ck9kj9m1u003615yl58rionnn",
        "name": "Assegai",
        "category": "Spears",
        "type": "",
        "dice": 2,
        "adds": "3",
        "strengthReq": 7,
        "dexReq": 12,
        "cost": 20,
        "weight": 50,
        "range": "30 yards",
        "length": "6'",
        "extraInfo": ""
    },
    {
        "id": "ck9kja1ym003715ylpnz58xx1",
        "name": "Javelin",
        "category": "Spears",
        "type": "",
        "dice": 2,
        "adds": "",
        "strengthReq": 5,
        "dexReq": 7,
        "cost": 10,
        "weight": 30,
        "range": "40 yards",
        "length": "6'",
        "extraInfo": ""
    },
    {
        "id": "ck9kjazr5003815ylpwdmx6g9",
        "name": "Sax",
        "category": "Daggers",
        "type": "",
        "dice": 2,
        "adds": "5",
        "strengthReq": 7,
        "dexReq": 10,
        "cost": 30,
        "weight": 25,
        "range": "",
        "length": "",
        "extraInfo": ""
    },
    {
        "id": "ck9kjd54v004115ylrifk6t5j",
        "name": "Kukri",
        "category": "Daggers",
        "type": "",
        "dice": 2,
        "adds": "5",
        "strengthReq": 6,
        "dexReq": 6,
        "cost": 30,
        "weight": 20,
        "range": "15 yards",
        "length": "",
        "extraInfo": ""
    },
    {
        "id": "ck9kjbj8r003915yl9uhtvs80",
        "name": "Katar",
        "category": "Daggers",
        "type": "",
        "dice": 2,
        "adds": "4",
        "strengthReq": 2,
        "dexReq": 8,
        "cost": 18,
        "weight": 22,
        "range": "",
        "length": "",
        "extraInfo": ""
    },
    {
        "id": "ck9kjch8m004015ylnzjavxhf",
        "name": "Haladie",
        "category": "Daggers",
        "type": "",
        "dice": 2,
        "adds": "4",
        "strengthReq": 2,
        "dexReq": 4,
        "cost": 25,
        "weight": 15,
        "range": "",
        "length": "",
        "extraInfo": ""
    }, {
        "id": "ck9kjnq08004215ylo8vlbhzc",
        "name": "†Cranequin (rack & pinion on arbalest)",
        "category": "Projectile Weapons",
        "type": "Class I: Arbalests & Crossbows",
        "dice": 8,
        "adds": "",
        "strengthReq": 15,
        "dexReq": 10,
        "cost": 600,
        "weight": 250,
        "range": "100 yards",
        "length": "",
        "extraInfo": ""
    }, {
        "id": "ck9kjp1oj004315ylnt5owhdv",
        "name": "†Arbalest (stirrup; lever drawn)",
        "category": "Projectile Weapons",
        "type": "Class I: Arbalests & Crossbows",
        "dice": 6,
        "adds": "3",
        "strengthReq": 17,
        "dexReq": 10,
        "cost": 400,
        "weight": 220,
        "range": "100 yards",
        "length": "",
        "extraInfo": ""
    }, {
        "id": "ck9kjqjjd004415yltrrbe1jl",
        "name": "†Crossbow (hand-drawn)",
        "category": "Projectile Weapons",
        "type": "Class I: Arbalests & Crossbows",
        "dice": 5,
        "adds": "",
        "strengthReq": 15,
        "dexReq": 10,
        "cost": 250,
        "weight": 180,
        "range": "100 yards",
        "length": "",
        "extraInfo": ""
    }, {
        "id": "ck9kk0scj004515ylxqbgd0zp",
        "name": "†Light crossbow (hand-drawn)",
        "category": "Projectile Weapons",
        "type": "Class I: Arbalests & Crossbows",
        "dice": 4,
        "adds": "",
        "strengthReq": 12,
        "dexReq": 10,
        "cost": 170,
        "weight": 120,
        "range": "90 yards",
        "length": "",
        "extraInfo": ""
    }, {
        "id": "ck9kk2i0n004615yl8xjavpsu",
        "name": "Ankus",
        "category": "Weird Weapons",
        "type": "",
        "dice": 2,
        "adds": "1",
        "strengthReq": 2,
        "dexReq": 11,
        "cost": 27,
        "weight": 50,
        "range": "",
        "length": "",
        "extraInfo": ""
    }, {
        "id": "ck9kk3fnx004715ylvod2qjjn",
        "name": "†Quarterstaff",
        "category": "Weird Weapons",
        "type": "",
        "dice": 2,
        "adds": "",
        "strengthReq": 2,
        "dexReq": 8,
        "cost": 10,
        "weight": 50,
        "range": "",
        "length": "",
        "extraInfo": ""
    }
];