export const weapons = [{
        "name": "†Great sword (6')",
        "category": "Swords",
        "type": "Class I: Straight Swords",
        "dice": 6,
        "adds": "",
        "strengthReq": 21,
        "dexReq": 18,
        "cost": 120,
        "weight": 170,
        "range": "",
        "length": "",
        "extraInfo": ""
    },
    {
        "name": "†Two-handed broadsword (5')",
        "category": "Swords",
        "type": "Class I: Straight Swords",
        "dice": 5,
        "adds": "2",
        "strengthReq": 21,
        "dexReq": 14,
        "cost": 110,
        "weight": 160,
        "range": "",
        "length": "",
        "extraInfo": ""
    },
    {
        "name": "Hand-and-a-half sword (4')",
        "category": "Swords",
        "type": "Class I: Straight Swords",
        "dice": 5,
        "adds": "",
        "strengthReq": 16,
        "dexReq": 12,
        "cost": 90,
        "weight": 150,
        "range": "",
        "length": "",
        "extraInfo": ""
    },
    {
        "name": "Broadsword (3'-4')",
        "category": "Swords",
        "type": "Class I: Straight Swords",
        "dice": 3,
        "adds": "4",
        "strengthReq": 15,
        "dexReq": 10,
        "cost": 70,
        "weight": 120,
        "range": "",
        "length": "",
        "extraInfo": ""
    },
    {
        "name": "Gladius (2.5'-3')",
        "category": "Swords",
        "type": "Class I: Straight Swords",
        "dice": 3,
        "adds": "2",
        "strengthReq": 10,
        "dexReq": 7,
        "cost": 50,
        "weight": 70,
        "range": "",
        "length": "",
        "extraInfo": ""
    },
    {
        "name": "Short sword (2'-2.5')",
        "category": "Swords",
        "type": "Class I: Straight Swords",
        "dice": 3,
        "adds": "",
        "strengthReq": 7,
        "dexReq": 3,
        "cost": 35,
        "weight": 30,
        "range": "",
        "length": "",
        "extraInfo": ""
    },
    {
        "name": "†Grand Shamsheer (No-datchi) (6') ",
        "category": "Swords",
        "type": "Class II: Curved Swords",
        "dice": 6,
        "adds": "2",
        "strengthReq": 22,
        "dexReq": 18,
        "cost": 135,
        "weight": 150,
        "range": "",
        "length": "",
        "extraInfo": ""
    },
    {
        "name": "†Double-bladed broad axe",
        "category": "Hafted Weapons",
        "type": "Class I: Slicing Heads",
        "dice": 6,
        "adds": "3",
        "strengthReq": 21,
        "dexReq": 10,
        "cost": 140,
        "weight": 220,
        "range": "",
        "length": "",
        "extraInfo": ""
    },
    {
        "name": "†Great axe (single blade)",
        "category": "Hafted Weapons",
        "type": "Class I: Slicing Heads",
        "dice": 5,
        "adds": "3",
        "strengthReq": 20,
        "dexReq": 10,
        "cost": 140,
        "weight": 220,
        "range": "",
        "length": "",
        "extraInfo": ""
    },
    {
        "name": "†Bullova",
        "category": "Hafted Weapons",
        "type": "Class I: Slicing Heads",
        "dice": 4,
        "adds": "3",
        "strengthReq": 16,
        "dexReq": 9,
        "cost": 100,
        "weight": 200,
        "range": "",
        "length": "",
        "extraInfo": ""
    },
    {
        "name": "Broadaxe (single blade)",
        "category": "Hafted Weapons",
        "type": "Class I: Slicing Heads",
        "dice": 4,
        "adds": "",
        "strengthReq": 17,
        "dexReq": 8,
        "cost": 100,
        "weight": 150,
        "range": "",
        "length": "",
        "extraInfo": ""
    },
    {
        "name": "Francisca",
        "category": "Hafted Weapons",
        "type": "Class I: Slicing Heads",
        "dice": 3,
        "adds": "2",
        "strengthReq": 9,
        "dexReq": 5,
        "cost": 70,
        "weight": 60,
        "range": "",
        "length": "",
        "extraInfo": "(can be thrown -- if so, DEX req. = 12, range = 25 yards)"
    },
    {
        "name": "Taper axe",
        "category": "Hafted Weapons",
        "type": "Class I: Slicing Heads",
        "dice": 3,
        "adds": "",
        "strengthReq": 8,
        "dexReq": 4,
        "cost": 50,
        "weight": 70,
        "range": "",
        "length": "",
        "extraInfo": ""
    },
    {
        "name": "†Bec de Corbin",
        "category": "Hafted Weapons",
        "type": "Class II: Stabbing Heads",
        "dice": 6,
        "adds": "",
        "strengthReq": 18,
        "dexReq": 10,
        "cost": 125,
        "weight": 175,
        "range": "",
        "length": "",
        "extraInfo": ""
    },
    {
        "name": "Poleaxe",
        "category": "Pole Weapons",
        "type": "",
        "dice": 7,
        "adds": "",
        "strengthReq": 14,
        "dexReq": 13,
        "cost": 210,
        "weight": 300,
        "range": "",
        "length": "10'",
        "extraInfo": ""
    },
    {
        "name": "Chauves souris",
        "category": "Pole Weapons",
        "type": "",
        "dice": 6,
        "adds": "5",
        "strengthReq": 15,
        "dexReq": 12,
        "cost": 250,
        "weight": 190,
        "range": "",
        "length": "12'",
        "extraInfo": ""
    },
    {
        "name": "Ranseur (runka)",
        "category": "Pole Weapons",
        "type": "",
        "dice": 6,
        "adds": "4",
        "strengthReq": 15,
        "dexReq": 10,
        "cost": 170,
        "weight": 180,
        "range": "",
        "length": "12'",
        "extraInfo": ""
    },
    {
        "name": "Halbard",
        "category": "Pole Weapons",
        "type": "",
        "dice": 6,
        "adds": "",
        "strengthReq": 16,
        "dexReq": 12,
        "cost": 200,
        "weight": 250,
        "range": "",
        "length": "10'",
        "extraInfo": ""
    },
    {
        "name": "Pike",
        "category": "Pole Weapons",
        "type": "",
        "dice": 6,
        "adds": "",
        "strengthReq": 15,
        "dexReq": 12,
        "cost": 160,
        "weight": 100,
        "range": "",
        "length": "12'",
        "extraInfo": ""
    },
    {
        "name": "Demi-lune (halfmoon)",
        "category": "Pole Weapons",
        "type": "",
        "dice": 5,
        "adds": "4",
        "strengthReq": 12,
        "dexReq": 20,
        "cost": 100,
        "weight": 150,
        "range": "",
        "length": "12'",
        "extraInfo": ""
    },
    {
        "name": "Voulge",
        "category": "Pole Weapons",
        "type": "",
        "dice": 5,
        "adds": "1",
        "strengthReq": 15,
        "dexReq": 9,
        "cost": 160,
        "weight": 200,
        "range": "",
        "length": "10'",
        "extraInfo": ""
    },
    {
        "name": "Voulge",
        "category": "Pole Weapons",
        "type": "",
        "dice": 5,
        "adds": "1",
        "strengthReq": 15,
        "dexReq": 9,
        "cost": 160,
        "weight": 200,
        "range": "",
        "length": "10'",
        "extraInfo": ""
    },
    {
        "name": "Fauchard",
        "category": "Pole Weapons",
        "type": "",
        "dice": 5,
        "adds": "",
        "strengthReq": 13,
        "dexReq": 10,
        "cost": 160,
        "weight": 180,
        "range": "",
        "length": "12'",
        "extraInfo": ""
    },
    {
        "name": "Partizan",
        "category": "Pole Weapons",
        "type": "",
        "dice": 4,
        "adds": "5",
        "strengthReq": 15,
        "dexReq": 9,
        "cost": 140,
        "weight": 200,
        "range": "",
        "length": "8'",
        "extraInfo": ""
    },
    {
        "name": "Guisarme",
        "category": "Pole Weapons",
        "type": "",
        "dice": 4,
        "adds": "4",
        "strengthReq": 14,
        "dexReq": 10,
        "cost": 135,
        "weight": 200,
        "range": "",
        "length": "9'",
        "extraInfo": ""
    },
    {
        "name": "Scythe (long)",
        "category": "Pole Weapons",
        "type": "",
        "dice": 4,
        "adds": "2",
        "strengthReq": 11,
        "dexReq": 7,
        "cost": 80,
        "weight": 150,
        "range": "",
        "length": "6'",
        "extraInfo": ""
    },
    {
        "name": "Billhook",
        "category": "Pole Weapons",
        "type": "",
        "dice": 4,
        "adds": "",
        "strengthReq": 14,
        "dexReq": 8,
        "cost": 120,
        "weight": 190,
        "range": "",
        "length": "11'",
        "extraInfo": ""
    },
    {
        "name": "Kumade (rake)",
        "category": "Pole Weapons",
        "type": "",
        "dice": 3,
        "adds": "3",
        "strengthReq": 10,
        "dexReq": 12,
        "cost": 75,
        "weight": 90,
        "range": "",
        "length": "5'",
        "extraInfo": ""
    },
    {
        "name": "Brandestock",
        "category": "Pole Weapons",
        "type": "",
        "dice": 3,
        "adds": "1",
        "strengthReq": 17,
        "dexReq": 10,
        "cost": 200,
        "weight": 150,
        "range": "",
        "length": "6'",
        "extraInfo": ""
    },
    {
        "name": "Extended Brandestock",
        "category": "Pole Weapons",
        "type": "",
        "dice": 4,
        "adds": "",
        "strengthReq": 19,
        "dexReq": 12,
        "cost": 280,
        "weight": 200,
        "range": "",
        "length": "9'",
        "extraInfo": ""
    },
    {
        "name": "Pilum",
        "category": "Spears",
        "type": "",
        "dice": 5,
        "adds": "",
        "strengthReq": 12,
        "dexReq": 8,
        "cost": 75,
        "weight": 100,
        "range": "20 yards",
        "length": "(5'-8')",
        "extraInfo": ""
    },
    {
        "name": "Trident",
        "category": "Spears",
        "type": "",
        "dice": 4,
        "adds": "3",
        "strengthReq": 10,
        "dexReq": 10,
        "cost": 60,
        "weight": 75,
        "range": "10 yards",
        "length": "6'",
        "extraInfo": ""
    },
    {
        "name": "Hoko",
        "category": "Spears",
        "type": "",
        "dice": 4,
        "adds": "1",
        "strengthReq": 10,
        "dexReq": 12,
        "cost": 55,
        "weight": 90,
        "range": "0",
        "length": "6'",
        "extraInfo": ""
    },
    {
        "name": "Oxtongue (hasta)",
        "category": "Spears",
        "type": "",
        "dice": 4,
        "adds": "",
        "strengthReq": 10,
        "dexReq": 5,
        "cost": 80,
        "weight": 70,
        "range": "0",
        "length": "6'",
        "extraInfo": "(best used from horseback -- if so, add 2 dice to its roll)"
    },
    {
        "name": "†Spontoon",
        "category": "Spears",
        "type": "",
        "dice": 3,
        "adds": "3",
        "strengthReq": 9,
        "dexReq": 9,
        "cost": 30,
        "weight": 100,
        "range": "0",
        "length": "8'",
        "extraInfo": ""
    },
    {
        "name": "Common spear",
        "category": "Spears",
        "type": "",
        "dice": 3,
        "adds": "1",
        "strengthReq": 8,
        "dexReq": 8,
        "cost": 22,
        "weight": 50,
        "range": "40 yards",
        "length": "6'",
        "extraInfo": ""
    },
    {
        "name": "Assegai",
        "category": "Spears",
        "type": "",
        "dice": 2,
        "adds": "3",
        "strengthReq": 7,
        "dexReq": 12,
        "cost": 20,
        "weight": 50,
        "range": "30 yards",
        "length": "6'",
        "extraInfo": ""
    },
    {
        "name": "Javelin",
        "category": "Spears",
        "type": "",
        "dice": 2,
        "adds": "",
        "strengthReq": 5,
        "dexReq": 7,
        "cost": 10,
        "weight": 30,
        "range": "40 yards",
        "length": "6'",
        "extraInfo": ""
    },
    {
        "name": "Sax",
        "category": "Daggers",
        "type": "",
        "dice": 2,
        "adds": "5",
        "strengthReq": 7,
        "dexReq": 10,
        "cost": 30,
        "weight": 25,
        "range": "",
        "length": "",
        "extraInfo": ""
    },
    {
        "name": "Kukri",
        "category": "Daggers",
        "type": "",
        "dice": 2,
        "adds": "5",
        "strengthReq": 6,
        "dexReq": 6,
        "cost": 30,
        "weight": 20,
        "range": "15 yards",
        "length": "",
        "extraInfo": ""
    },
    {
        "name": "Katar",
        "category": "Daggers",
        "type": "",
        "dice": 2,
        "adds": "4",
        "strengthReq": 2,
        "dexReq": 8,
        "cost": 18,
        "weight": 22,
        "range": "",
        "length": "",
        "extraInfo": ""
    },
    {
        "name": "Haladie",
        "category": "Daggers",
        "type": "",
        "dice": 2,
        "adds": "4",
        "strengthReq": 2,
        "dexReq": 4,
        "cost": 25,
        "weight": 15,
        "range": "",
        "length": "",
        "extraInfo": ""
    }, {
        "name": "†Cranequin (rack & pinion on arbalest)",
        "category": "Projectile Weapons",
        "type": "Class I: Arbalests & Crossbows",
        "dice": 8,
        "adds": "",
        "strengthReq": 15,
        "dexReq": 10,
        "cost": 600,
        "weight": 250,
        "range": "100 yards",
        "length": "",
        "extraInfo": ""
    }, {
        "name": "†Arbalest (stirrup; lever drawn)",
        "category": "Projectile Weapons",
        "type": "Class I: Arbalests & Crossbows",
        "dice": 6,
        "adds": "3",
        "strengthReq": 17,
        "dexReq": 10,
        "cost": 400,
        "weight": 220,
        "range": "100 yards",
        "length": "",
        "extraInfo": ""
    }, {
        "name": "†Crossbow (hand-drawn)",
        "category": "Projectile Weapons",
        "type": "Class I: Arbalests & Crossbows",
        "dice": 5,
        "adds": "",
        "strengthReq": 15,
        "dexReq": 10,
        "cost": 250,
        "weight": 180,
        "range": "100 yards",
        "length": "",
        "extraInfo": ""
    }, {
        "name": "†Light crossbow (hand-drawn)",
        "category": "Projectile Weapons",
        "type": "Class I: Arbalests & Crossbows",
        "dice": 4,
        "adds": "",
        "strengthReq": 12,
        "dexReq": 10,
        "cost": 170,
        "weight": 120,
        "range": "90 yards",
        "length": "",
        "extraInfo": ""
    }, {
        "name": "Ankus",
        "category": "Weird Weapons",
        "type": "",
        "dice": 2,
        "adds": "1",
        "strengthReq": 2,
        "dexReq": 11,
        "cost": 27,
        "weight": 50,
        "range": "",
        "length": "",
        "extraInfo": ""
    }, {
        "name": "†Quarterstaff",
        "category": "Weird Weapons",
        "type": "",
        "dice": 2,
        "adds": "",
        "strengthReq": 2,
        "dexReq": 8,
        "cost": 10,
        "weight": 50,
        "range": "",
        "length": "",
        "extraInfo": ""
    }
];